// Command genblocks generates the per-block-state classification table used by
// the bot's world (physics + pathfinder).
//
// Mode 1 — minecraft-data only (state IDs and shapes from PrismarineJS):
//
//	go run ./internal/tools/genblocks -data <dir with blocks.json and blockCollisionShapes.json> \
//	    -version 1.21.11 -out internal/protocol/versions/v774/blocks.go -pkg v774
//
// Mode 2 — Mojang report (preferred). State IDs come from the vanilla data
// generator's reports/blocks.json; collision shapes are looked up by block
// name and state offset in a minecraft-data release of the same or an
// earlier version. Blocks missing there are classified from their Mojang
// block type (see newBlockTypes) or the run fails, listing them.
//
//	java -DbundlerMainClass=net.minecraft.data.Main -jar server.jar --reports --output gen
//	go run ./internal/tools/genblocks -mojang gen/reports/blocks.json -data <minecraft-data pc/26.1> -mdversion 26.1 \
//	    -version 26.2 -out internal/protocol/versions/v776/blocks.go -pkg v776
//
// minecraft-data: https://github.com/PrismarineJS/minecraft-data/tree/master/data/pc/<version>
package main

import (
	"bytes"
	"compress/zlib"
	"encoding/base64"
	"encoding/binary"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"log"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Class codes. Must match the order of bot.BlockType.
const (
	classAir       = '0'
	classSolid     = '1'
	classWater     = '2'
	classClimbable = '3'
	classDangerous = '4'
)

// Blocks whose class does not follow from the collision shape alone.
var (
	waterBlocks = set("water", "bubble_column", "kelp", "kelp_plant", "seagrass", "tall_seagrass")
	climbable   = set("ladder", "vine", "twisting_vines", "twisting_vines_plant",
		"weeping_vines", "weeping_vines_plant", "cave_vines", "cave_vines_plant")
	// Hazards without a collision box. Hazards that have one (cactus, magma_block,
	// campfire) stay solid so physics never falls through them.
	dangerous = set("lava", "fire", "soul_fire", "sweet_berry_bush", "wither_rose",
		"powder_snow", "cobweb")
)

// Mojang block types (blocks.json "definition.type") that are full-collision
// blocks. Used only for blocks that minecraft-data does not know yet.
var newBlockTypes = map[string]byte{
	"minecraft:block":         classSolid,
	"minecraft:slab":          classSolid,
	"minecraft:stair":         classSolid,
	"minecraft:wall":          classSolid,
	"minecraft:potent_sulfur": classSolid, // BaseEntityBlock with the default full cube
	"minecraft:sulfur_spike":  classSolid, // SpeleothemBlock, like pointed_dripstone
}

// Vanilla blocks whose collision shapes new blocks of a Mojang block type
// share, state for state (same properties in the same order).
var referenceBlocks = map[string]string{
	"minecraft:slab":         "stone_slab",
	"minecraft:stair":        "stone_stairs",
	"minecraft:wall":         "cobblestone_wall",
	"minecraft:sulfur_spike": "pointed_dripstone",
}

type mojangBlock struct {
	Definition struct {
		Type string `json:"type"`
	} `json:"definition"`
	States []struct {
		ID int `json:"id"`
	} `json:"states"`
}

type block struct {
	Name       string `json:"name"`
	MinStateID int    `json:"minStateId"`
	MaxStateID int    `json:"maxStateId"`
}

type shapes struct {
	Blocks map[string]json.RawMessage `json:"blocks"` // int or []int (per state)
	Shapes map[string][][]float64     `json:"shapes"`
}

func main() {
	dataDir := flag.String("data", "", "directory containing blocks.json and blockCollisionShapes.json")
	version := flag.String("version", "", "Minecraft version the data belongs to (for the header)")
	out := flag.String("out", "", "output Go file")
	pkg := flag.String("pkg", "", "output package name")
	mojang := flag.String("mojang", "", "optional: Mojang reports/blocks.json for state IDs (mode 2)")
	mdVersion := flag.String("mdversion", "", "mode 2: minecraft-data version the -data dir holds, for the header (e.g. 26.1)")
	flag.Parse()
	if *dataDir == "" || *out == "" || *pkg == "" || *version == "" {
		flag.Usage()
		os.Exit(2)
	}

	var blocks []block
	mustLoad(filepath.Join(*dataDir, "blocks.json"), &blocks)
	var sh shapes
	mustLoad(filepath.Join(*dataDir, "blockCollisionShapes.json"), &sh)

	var table []byte
	var shapeOf []int
	source := "PrismarineJS/minecraft-data pc/" + *version
	if *mojang != "" {
		table, shapeOf = fromMojang(*mojang, blocks, sh)
		md := *mdVersion
		if md == "" {
			md = filepath.Base(filepath.Clean(*dataDir))
		}
		source = "Mojang reports/blocks.json (" + *version + ") + collision shapes from PrismarineJS/minecraft-data pc/" + md
	} else {
		table, shapeOf = fromMinecraftData(blocks, sh)
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by internal/tools/genblocks from %s. DO NOT EDIT.\n\n", source)
	writeTable(&buf, *pkg, table)
	writeShapes(&buf, shapeOf, sh)

	src, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("format: %v", err)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		log.Fatal(err)
	}
	log.Printf("wrote %d block states to %s", len(table), *out)
}

func fromMinecraftData(blocks []block, sh shapes) ([]byte, []int) {
	maxState := 0
	for _, b := range blocks {
		maxState = max(maxState, b.MaxStateID)
	}
	table := bytes.Repeat([]byte{classSolid}, maxState+1)
	shapeOf := filled(maxState+1, shapeFull)

	for _, b := range blocks {
		n := b.MaxStateID - b.MinStateID + 1
		shapeIDs, err := shapeIDsFor(sh.Blocks[b.Name], n)
		if err != nil {
			log.Fatalf("%s: %v", b.Name, err)
		}
		for i := 0; i < n; i++ {
			table[b.MinStateID+i] = classify(b.Name, len(sh.Shapes[fmt.Sprint(shapeIDs[i])]) > 0)
			shapeOf[b.MinStateID+i] = shapeIDs[i]
		}
	}
	return table, shapeOf
}

// fromMojang builds the table from Mojang's state IDs. A block's states are
// matched to minecraft-data by block name and offset from the block's first
// state; the state count must agree.
func fromMojang(path string, mdBlocks []block, sh shapes) ([]byte, []int) {
	var report map[string]mojangBlock
	mustLoad(path, &report)

	byName := make(map[string]block, len(mdBlocks))
	for _, b := range mdBlocks {
		byName[b.Name] = b
	}

	maxState := 0
	for _, b := range report {
		for _, st := range b.States {
			maxState = max(maxState, st.ID)
		}
	}
	table := bytes.Repeat([]byte{classSolid}, maxState+1)
	shapeOf := filled(maxState+1, shapeFull)
	var unknown []string
	fallback := 0

	for key, b := range report {
		name := strings.TrimPrefix(key, "minecraft:")
		n := len(b.States)
		first := b.States[0].ID
		for i, st := range b.States {
			if st.ID != first+i {
				log.Fatalf("%s: state IDs are not contiguous", key)
			}
		}

		md, ok := byName[name]
		if ok && md.MaxStateID-md.MinStateID+1 != n {
			log.Fatalf("%s: %d states in the Mojang report, %d in minecraft-data", key, n, md.MaxStateID-md.MinStateID+1)
		}
		if !ok {
			class, known := newBlockTypes[b.Definition.Type]
			if !known {
				unknown = append(unknown, fmt.Sprintf("%s (type %s)", key, b.Definition.Type))
				continue
			}
			shape := shapeEmpty
			if class == classSolid {
				shape = shapeFull
			}
			var refShapes []int
			if ref, ok := byName[referenceBlocks[b.Definition.Type]]; ok && ref.MaxStateID-ref.MinStateID+1 == n {
				ids, err := shapeIDsFor(sh.Blocks[ref.Name], n)
				if err != nil {
					log.Fatalf("%s: reference %s: %v", key, ref.Name, err)
				}
				refShapes = ids
			}
			class = classify(name, class == classSolid)
			for i := 0; i < n; i++ {
				table[first+i] = class
				shapeOf[first+i] = shape
				if refShapes != nil {
					shapeOf[first+i] = refShapes[i]
				}
			}
			fallback++
			continue
		}

		shapeIDs, err := shapeIDsFor(sh.Blocks[name], n)
		if err != nil {
			log.Fatalf("%s: %v", name, err)
		}
		for i := 0; i < n; i++ {
			table[first+i] = classify(name, len(sh.Shapes[fmt.Sprint(shapeIDs[i])]) > 0)
			shapeOf[first+i] = shapeIDs[i]
		}
	}
	if len(unknown) > 0 {
		sort.Strings(unknown)
		log.Fatalf("blocks missing from minecraft-data with no known type; add them to newBlockTypes:\n  %s",
			strings.Join(unknown, "\n  "))
	}
	log.Printf("%d blocks classified from their Mojang block type (not in minecraft-data)", fallback)
	return table, shapeOf
}

func writeTable(buf *bytes.Buffer, pkg string, table []byte) {
	fmt.Fprintf(buf, "package %s\n\n", pkg)
	fmt.Fprintf(buf, "// BlockClasses holds one class per block state ID (index = state ID):\n")
	fmt.Fprintf(buf, "// '0' air, '1' solid, '2' water, '3' climbable, '4' dangerous.\n")
	fmt.Fprintf(buf, "const BlockClasses = \"\" +\n")
	const lineLen = 100
	for i := 0; i < len(table); i += lineLen {
		end := min(i+lineLen, len(table))
		sep := " +"
		if end == len(table) {
			sep = ""
		}
		fmt.Fprintf(buf, "\t%q%s\n", table[i:end], sep)
	}
}

func classify(name string, hasCollision bool) byte {
	switch {
	case waterBlocks[name]:
		return classWater
	case climbable[name]:
		return classClimbable
	case dangerous[name]:
		return classDangerous
	case hasCollision:
		return classSolid
	default:
		return classAir // air, cave_air, void_air, plants, torches, signs, ...
	}
}

// shapeIDsFor expands a blockCollisionShapes entry to one shape ID per state.
func shapeIDsFor(raw json.RawMessage, n int) ([]int, error) {
	if raw == nil {
		return nil, fmt.Errorf("no collision shape entry")
	}
	var single int
	if err := json.Unmarshal(raw, &single); err == nil {
		ids := make([]int, n)
		for i := range ids {
			ids[i] = single
		}
		return ids, nil
	}
	var ids []int
	if err := json.Unmarshal(raw, &ids); err != nil {
		return nil, err
	}
	if len(ids) != n {
		return nil, fmt.Errorf("got %d shape IDs for %d states", len(ids), n)
	}
	return ids, nil
}

func mustLoad(path string, v any) {
	data, err := os.ReadFile(path)
	if err != nil {
		log.Fatal(err)
	}
	if err := json.Unmarshal(data, v); err != nil {
		log.Fatalf("%s: %v", path, err)
	}
}

func set(names ...string) map[string]bool {
	m := make(map[string]bool, len(names))
	for _, n := range names {
		m[n] = true
	}
	return m
}

// Placeholder shape IDs for blocks minecraft-data does not know.
const (
	shapeFull  = -1
	shapeEmpty = -2
)

func filled(n, v int) []int {
	s := make([]int, n)
	for i := range s {
		s[i] = v
	}
	return s
}

// writeShapes writes BlockShapes: the collision boxes of every block state,
// zlib-compressed and base64-encoded (decoded by the bot at runtime).
//
// Layout (little endian):
//
//	u16 shape count, then per shape: u8 box count, per box 6 x int8
//	    (minX minY minZ maxX maxY maxZ in 1/64 block)
//	u32 state count, u32 run count, then per run: u16 states, u16 shape index
//
// Shape 0 is empty and shape 1 the full cube.
func writeShapes(buf *bytes.Buffer, shapeOf []int, sh shapes) {
	type box [6]int8
	var shapeList [][]box
	index := map[string]uint16{}
	add := func(boxes []box) uint16 {
		key := fmt.Sprint(boxes)
		if i, ok := index[key]; ok {
			return i
		}
		i := uint16(len(shapeList))
		index[key] = i
		shapeList = append(shapeList, boxes)
		return i
	}
	full := []box{{0, 0, 0, 64, 64, 64}}
	add(nil)
	add(full)

	convert := func(id int) []box {
		switch id {
		case shapeFull:
			return full
		case shapeEmpty:
			return nil
		}
		raw, ok := sh.Shapes[fmt.Sprint(id)]
		if !ok {
			log.Fatalf("shape %d missing", id)
		}
		var boxes []box
		for _, b := range raw {
			var q box
			for i, c := range b {
				v := c * 64
				if v != math.Round(v) || v < -128 || v > 127 {
					log.Fatalf("shape %d: coordinate %v is not a multiple of 1/64 in range", id, c)
				}
				q[i] = int8(v)
			}
			boxes = append(boxes, q)
		}
		return boxes
	}

	perState := make([]uint16, len(shapeOf))
	for i, id := range shapeOf {
		perState[i] = add(convert(id))
	}

	var raw bytes.Buffer
	le := binary.LittleEndian
	binary.Write(&raw, le, uint16(len(shapeList)))
	for _, boxes := range shapeList {
		raw.WriteByte(byte(len(boxes)))
		for _, b := range boxes {
			binary.Write(&raw, le, b)
		}
	}
	type run struct{ n, shape uint16 }
	var runs []run
	for _, s := range perState {
		if len(runs) > 0 && runs[len(runs)-1].shape == s && runs[len(runs)-1].n < math.MaxUint16 {
			runs[len(runs)-1].n++
			continue
		}
		runs = append(runs, run{1, s})
	}
	binary.Write(&raw, le, uint32(len(perState)))
	binary.Write(&raw, le, uint32(len(runs)))
	for _, r := range runs {
		binary.Write(&raw, le, r)
	}

	var z bytes.Buffer
	zw, _ := zlib.NewWriterLevel(&z, zlib.BestCompression)
	zw.Write(raw.Bytes())
	zw.Close()
	enc := base64.StdEncoding.EncodeToString(z.Bytes())

	fmt.Fprintf(buf, "\n// BlockShapes holds the collision boxes of every block state (%d shapes,\n", len(shapeList))
	fmt.Fprintf(buf, "// %d runs), zlib-compressed and base64-encoded. See internal/tools/genblocks.\n", len(runs))
	fmt.Fprintf(buf, "const BlockShapes = \"\" +\n")
	const lineLen = 100
	for i := 0; i < len(enc); i += lineLen {
		end := min(i+lineLen, len(enc))
		sep := " +"
		if end == len(enc) {
			sep = ""
		}
		fmt.Fprintf(buf, "\t%q%s\n", enc[i:end], sep)
	}
	log.Printf("%d collision shapes, %d runs, %d bytes encoded", len(shapeList), len(runs), len(enc))
}
