// Command genblocks generates the per-block-state classification table used by
// bot.ClassifyBlock from PrismarineJS/minecraft-data files.
//
//	go run ./internal/tools/genblocks -data <dir with blocks.json and blockCollisionShapes.json> \
//	    -version 1.21.11 -out internal/protocol/versions/v774/blocks.go -pkg v774
//
// Data source: https://github.com/PrismarineJS/minecraft-data/tree/master/data/pc/<version>
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
)

// Class codes. Must match the order of bot.BlockType.
const (
	classAir       = '0'
	classSolid     = '1'
	classWater     = '2'
	classClimbable = '3'
	classDangerous = '4'
)

// Blocks whose class does not follow from the collision shape alone.
var (
	waterBlocks = set("water", "bubble_column", "kelp", "kelp_plant", "seagrass", "tall_seagrass")
	climbable   = set("ladder", "vine", "twisting_vines", "twisting_vines_plant",
		"weeping_vines", "weeping_vines_plant", "cave_vines", "cave_vines_plant")
	// Hazards without a collision box. Hazards that have one (cactus, magma_block,
	// campfire) stay solid so physics never falls through them.
	dangerous = set("lava", "fire", "soul_fire", "sweet_berry_bush", "wither_rose",
		"powder_snow", "cobweb")
)

type block struct {
	Name       string `json:"name"`
	MinStateID int    `json:"minStateId"`
	MaxStateID int    `json:"maxStateId"`
}

type shapes struct {
	Blocks map[string]json.RawMessage `json:"blocks"` // int or []int (per state)
	Shapes map[string][][]float64     `json:"shapes"`
}

func main() {
	dataDir := flag.String("data", "", "directory containing blocks.json and blockCollisionShapes.json")
	version := flag.String("version", "", "Minecraft version the data belongs to (for the header)")
	out := flag.String("out", "", "output Go file")
	pkg := flag.String("pkg", "", "output package name")
	flag.Parse()
	if *dataDir == "" || *out == "" || *pkg == "" || *version == "" {
		flag.Usage()
		os.Exit(2)
	}

	var blocks []block
	mustLoad(filepath.Join(*dataDir, "blocks.json"), &blocks)
	var sh shapes
	mustLoad(filepath.Join(*dataDir, "blockCollisionShapes.json"), &sh)

	maxState := 0
	for _, b := range blocks {
		maxState = max(maxState, b.MaxStateID)
	}
	table := bytes.Repeat([]byte{classSolid}, maxState+1)

	for _, b := range blocks {
		n := b.MaxStateID - b.MinStateID + 1
		shapeIDs, err := shapeIDsFor(sh.Blocks[b.Name], n)
		if err != nil {
			log.Fatalf("%s: %v", b.Name, err)
		}
		for i := 0; i < n; i++ {
			table[b.MinStateID+i] = classify(b.Name, len(sh.Shapes[fmt.Sprint(shapeIDs[i])]) > 0)
		}
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by internal/tools/genblocks from PrismarineJS/minecraft-data pc/%s. DO NOT EDIT.\n\n", *version)
	fmt.Fprintf(&buf, "package %s\n\n", *pkg)
	fmt.Fprintf(&buf, "// BlockClasses holds one class per block state ID (index = state ID):\n")
	fmt.Fprintf(&buf, "// '0' air, '1' solid, '2' water, '3' climbable, '4' dangerous.\n")
	fmt.Fprintf(&buf, "const BlockClasses = \"\" +\n")
	const lineLen = 100
	for i := 0; i < len(table); i += lineLen {
		end := min(i+lineLen, len(table))
		sep := " +"
		if end == len(table) {
			sep = ""
		}
		fmt.Fprintf(&buf, "\t%q%s\n", table[i:end], sep)
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("format: %v", err)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		log.Fatal(err)
	}
	log.Printf("wrote %d block states to %s", len(table), *out)
}

func classify(name string, hasCollision bool) byte {
	switch {
	case waterBlocks[name]:
		return classWater
	case climbable[name]:
		return classClimbable
	case dangerous[name]:
		return classDangerous
	case hasCollision:
		return classSolid
	default:
		return classAir // air, cave_air, void_air, plants, torches, signs, ...
	}
}

// shapeIDsFor expands a blockCollisionShapes entry to one shape ID per state.
func shapeIDsFor(raw json.RawMessage, n int) ([]int, error) {
	if raw == nil {
		return nil, fmt.Errorf("no collision shape entry")
	}
	var single int
	if err := json.Unmarshal(raw, &single); err == nil {
		ids := make([]int, n)
		for i := range ids {
			ids[i] = single
		}
		return ids, nil
	}
	var ids []int
	if err := json.Unmarshal(raw, &ids); err != nil {
		return nil, err
	}
	if len(ids) != n {
		return nil, fmt.Errorf("got %d shape IDs for %d states", len(ids), n)
	}
	return ids, nil
}

func mustLoad(path string, v any) {
	data, err := os.ReadFile(path)
	if err != nil {
		log.Fatal(err)
	}
	if err := json.Unmarshal(data, v); err != nil {
		log.Fatalf("%s: %v", path, err)
	}
}

func set(names ...string) map[string]bool {
	m := make(map[string]bool, len(names))
	for _, n := range names {
		m[n] = true
	}
	return m
}
