// Code generated by internal/tools/genpackets from Mojang reports/packets.json (26.2). DO NOT EDIT.

package v776

import "github.com/deware-pk/go-mcbots/internal/protocol/types"

// IDs are the packet IDs of Minecraft 26.2.
var IDs = types.PacketIDs{
	SB_Handshake:                0x00, // handshake serverbound minecraft:intention
	SB_LoginStart:               0x00, // login serverbound minecraft:hello
	SB_LoginAck:                 0x03, // login serverbound minecraft:login_acknowledged
	CB_LoginSuccess:             0x02, // login clientbound minecraft:login_finished
	CB_Disconnect:               0x00, // login clientbound minecraft:login_disconnect
	CB_SetCompression:           0x03, // login clientbound minecraft:login_compression
	CB_LoginPluginRequest:       0x04, // login clientbound minecraft:custom_query
	SB_LoginPluginResponse:      0x02, // login serverbound minecraft:custom_query_answer
	CB_CookieRequest_Login:      0x05, // login clientbound minecraft:cookie_request
	SB_CookieResponse_Login:     0x04, // login serverbound minecraft:cookie_response
	SB_KnownPacks:               0x07, // configuration serverbound minecraft:select_known_packs
	SB_FinishConfig:             0x03, // configuration serverbound minecraft:finish_configuration
	SB_PluginResponse:           0x02, // configuration serverbound minecraft:custom_payload
	CB_KnownPacks:               0x0E, // configuration clientbound minecraft:select_known_packs
	CB_RegistryData:             0x07, // configuration clientbound minecraft:registry_data
	CB_FinishConfig:             0x03, // configuration clientbound minecraft:finish_configuration
	CB_PluginRequest:            0x01, // configuration clientbound minecraft:custom_payload
	CB_Disconnect_Config:        0x02, // configuration clientbound minecraft:disconnect
	CB_KeepAlive_Config:         0x04, // configuration clientbound minecraft:keep_alive
	SB_KeepAlive_Config:         0x04, // configuration serverbound minecraft:keep_alive
	CB_FeatureFlags:             0x0C, // configuration clientbound minecraft:update_enabled_features
	SB_ClientInformation_Config: 0x00, // configuration serverbound minecraft:client_information
	CB_Ping_Config:              0x05, // configuration clientbound minecraft:ping
	SB_Pong_Config:              0x05, // configuration serverbound minecraft:pong
	CB_ResourcePackPush_Config:  0x09, // configuration clientbound minecraft:resource_pack_push
	SB_ResourcePack_Config:      0x06, // configuration serverbound minecraft:resource_pack
	CB_CookieRequest_Config:     0x00, // configuration clientbound minecraft:cookie_request
	SB_CookieResponse_Config:    0x01, // configuration serverbound minecraft:cookie_response
	CB_CodeOfConduct:            0x13, // configuration clientbound minecraft:code_of_conduct
	SB_AcceptCodeOfConduct:      0x09, // configuration serverbound minecraft:accept_code_of_conduct
	SB_AcceptTeleport:           0x00, // play serverbound minecraft:accept_teleportation
	SB_ChatCommand:              0x07, // play serverbound minecraft:chat_command
	SB_Chat:                     0x09, // play serverbound minecraft:chat
	SB_ClientCommand:            0x0C, // play serverbound minecraft:client_command
	SB_ClientTickEnd:            0x0D, // play serverbound minecraft:client_tick_end
	SB_ClientInformation:        0x0E, // play serverbound minecraft:client_information
	SB_KeepAlive:                0x1C, // play serverbound minecraft:keep_alive
	SB_PlayerPosition:           0x1E, // play serverbound minecraft:move_player_pos
	SB_PlayerPositionRotation:   0x1F, // play serverbound minecraft:move_player_pos_rot
	SB_PlayerRotation:           0x20, // play serverbound minecraft:move_player_rot
	SB_PlayerOnGround:           0x21, // play serverbound minecraft:move_player_status_only
	SB_PlayerCommand:            0x2A, // play serverbound minecraft:player_command
	SB_PlayerAction:             0x29, // play serverbound minecraft:player_action
	SB_PlayerInput:              0x2B, // play serverbound minecraft:player_input
	SB_ChunkBatchReceived:       0x0B, // play serverbound minecraft:chunk_batch_received
	SB_PlayerLoaded:             0x2C, // play serverbound minecraft:player_loaded
	SB_UseItem:                  0x43, // play serverbound minecraft:use_item
	SB_ConfigurationAck:         0x10, // play serverbound minecraft:configuration_acknowledged
	SB_Pong:                     0x2D, // play serverbound minecraft:pong
	SB_ResourcePack:             0x31, // play serverbound minecraft:resource_pack
	SB_CookieResponse:           0x15, // play serverbound minecraft:cookie_response
	CB_ChunkBatchFinished:       0x0B, // play clientbound minecraft:chunk_batch_finished
	CB_ChunkBatchStart:          0x0C, // play clientbound minecraft:chunk_batch_start
	CB_SpawnEntity:              0x01, // play clientbound minecraft:add_entity
	CB_SectionBlocksUpdate:      0x54, // play clientbound minecraft:section_blocks_update
	CB_BlockUpdate:              0x08, // play clientbound minecraft:block_update
	CB_Disconnect_Play:          0x20, // play clientbound minecraft:disconnect
	CB_UnloadChunk:              0x25, // play clientbound minecraft:forget_level_chunk
	CB_GameEvent:                0x26, // play clientbound minecraft:game_event
	CB_KeepAlive:                0x2C, // play clientbound minecraft:keep_alive
	CB_ChunkData:                0x2D, // play clientbound minecraft:level_chunk_with_light
	CB_Login:                    0x31, // play clientbound minecraft:login
	CB_PlayerChat:               0x41, // play clientbound minecraft:player_chat
	CB_CombatDeath:              0x44, // play clientbound minecraft:player_combat_kill
	CB_SyncPosition:             0x48, // play clientbound minecraft:player_position
	CB_Respawn:                  0x52, // play clientbound minecraft:respawn
	CB_SetDefaultSpawnPosition:  0x61, // play clientbound minecraft:set_default_spawn_position
	CB_UpdateHealth:             0x68, // play clientbound minecraft:set_health
	CB_SystemChat:               0x79, // play clientbound minecraft:system_chat
	CB_SetEntityMotion:          0x65, // play clientbound minecraft:set_entity_motion
	CB_Explode:                  0x24, // play clientbound minecraft:explode
	CB_StartConfiguration:       0x76, // play clientbound minecraft:start_configuration
	CB_Ping:                     0x3D, // play clientbound minecraft:ping
	CB_ResourcePackPush:         0x51, // play clientbound minecraft:resource_pack_push
	CB_CookieRequest:            0x15, // play clientbound minecraft:cookie_request
}
